# Generated by Django 6.0.4 on 2026-04-15 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('element_type', models.CharField(choices=[('fire', 'Fuego'), ('grass', 'Planta'), ('water', 'Agua')], max_length=10)),
                ('description', models.TextField()),
                ('emoji', models.CharField(max_length=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Creature',
                'verbose_name_plural': 'Creatures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=12)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Time slot',
                'verbose_name_plural': 'Time slots',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('weekday', 'start_time', 'end_time'), name='unique_time_slot_block'), models.CheckConstraint(condition=models.Q(('max_capacity__gt', 0)), name='timeslot_max_capacity_gt_0'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='timeslot_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.creature')),
                ('trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.timeslot')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
